name: build and release
on:
  push:
    branches:
      - main
      - build-and-release
    tags:
      - "**"


jobs:
  build_n_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup-node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: install dependecies
        run: npm install

      # - name: load auth_config.json
      #   run: echo '${{ secrets.AUTH_CONFIG }}' > src/auth_config.json

      # - name: buid 
      #   # skiping fail on warning for now
      #   run: CI=false npm run build

      # - name: archive
      #   run: tar zvcf build.tgz build

      # - name: Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     files: build.tgz
      #     prerelease: ${{ !startsWith(github.ref, 'refs/tags/') }}