name: build and release
on:
  push:
    branches:
      - main
      - build-and-release
    tags:
      - "**"


jobs:
  build_n_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup-node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: install dependecies
        run: npm install

      - name: buid 
        run: npm run build

      - name: archive
        run: tar zvcf build.tgz build

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build.tgz
          prerelease: ${{ !startsWith(github.ref, 'refs/tags/') }}